### ISSUE TITLE
"Permission Denied" on http://getdunne.net/wiki/doku.php?id=vanillajuce

### ISSUE THREAD

**Issue by McMartin** [getdunne/VanillaJuce#1]
When going to http://getdunne.net/wiki/doku.php?id=vanillajuce, I get the following page:
![image](https://user-images.githubusercontent.com/747995/29911629-d364d2a4-8e2e-11e7-9e10-73f19d143b6a.png)

Am I expected to register?

I am using Chrome Version 60.0.3112.113 on Windows 10.

**Comment by getdunne** [comment]
Whoops! Thank you. That's fixed now.

**Comment by McMartin** [comment]
Great! Thanks.
